package com.example.quizapp.ui.theme

import androidx.compose.ui.graphics.Color


//Defining set of colors using 'Color' class
val md_theme_light_primary = Color(0xFF006590)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)

val md_theme_light_primaryContainer = Color(0xFFC8E6FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001E2E)
val md_theme_light_secondary = Color(0xFF5A51B1)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE4DFFF)
val md_theme_light_onSecondaryContainer = Color(0xFF150067)
val md_theme_light_tertiary = Color(0xFF006879)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFAAEDFF)
val md_theme_light_onTertiaryContainer = Color(0xFF001F26)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFCFF)
val md_theme_light_onBackground = Color(0xFF001F2A)
val md_theme_light_surface = Color(0xFFFAFCFF)
val md_theme_light_onSurface = Color(0xFF001F2A)
val md_theme_light_surfaceVariant = Color(0xFFDDE3EA)
val md_theme_light_onSurfaceVariant = Color(0xFF41484D)
val md_theme_light_outline = Color(0xFF71787E)
val md_theme_light_inverseOnSurface = Color(0xFFE1F4FF)
val md_theme_light_inverseSurface = Color(0xFF003547)
val md_theme_light_inversePrimary = Color(0xFF87CEFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006590)
val md_theme_light_outlineVariant = Color(0xFFC1C7CE)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF87CEFF)
val md_theme_dark_onPrimary = Color(0xFF00344D)
val md_theme_dark_primaryContainer = Color(0xFF004C6D)
val md_theme_dark_onPrimaryContainer = Color(0xFFC8E6FF)
val md_theme_dark_secondary = Color(0xFFC5C0FF)
val md_theme_dark_onSecondary = Color(0xFF2A1E80)
val md_theme_dark_secondaryContainer = Color(0xFF423897)
val md_theme_dark_onSecondaryContainer = Color(0xFFE4DFFF)
val md_theme_dark_tertiary = Color(0xFF54D6F3)
val md_theme_dark_onTertiary = Color(0xFF003640)
val md_theme_dark_tertiaryContainer = Color(0xFF004E5C)
val md_theme_dark_onTertiaryContainer = Color(0xFFAAEDFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F2A)
val md_theme_dark_onBackground = Color(0xFFBFE9FF)
val md_theme_dark_surface = Color(0xFF001F2A)
val md_theme_dark_onSurface = Color(0xFFBFE9FF)
val md_theme_dark_surfaceVariant = Color(0xFF41484D)
val md_theme_dark_onSurfaceVariant = Color(0xFFC1C7CE)
val md_theme_dark_outline = Color(0xFF8B9198)
val md_theme_dark_inverseOnSurface = Color(0xFF001F2A)
val md_theme_dark_inverseSurface = Color(0xFFBFE9FF)
val md_theme_dark_inversePrimary = Color(0xFF006590)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF87CEFF)
val md_theme_dark_outlineVariant = Color(0xFF41484D)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF0077A9)
val Text = Color(0xFF001429)
val light_Text = Color(0xFF0A61A4)
val light_onText = Color(0xFFFFFFFF)
val light_TextContainer = Color(0xFFD2E4FF)
val light_onTextContainer = Color(0xFF001C37)
val dark_Text = Color(0xFFA0CAFF)
val dark_onText = Color(0xFF003259)
val dark_TextContainer = Color(0xFF00497E)
val dark_onTextContainer = Color(0xFFD2E4FF)